services:
  - type: web
    name: noordzee-proxy
    runtime: python
    buildCommand: pip install --upgrade pip
    startCommand: python3 rws-proxy.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
