services:
  - type: web
    name: noordzee-proxy
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install --upgrade pip
    startCommand: python3 rws-proxy.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: MVB_USERNAME
        sync: false   # in te vullen via Render dashboard
      - key: MVB_PASSWORD
        sync: false   # in te vullen via Render dashboard
